### ISSUE TITLE
Various comment formatting

### ISSUE THREAD

**Issue by patpragman** [CorpHackRyan/RP-Spaceoids#15]
Pat (like an asshole) did multiple lines of # on several lines instead of """ """ style comments, just use the multiline comments instead!

**Comment by patpragman** [comment]
Cleaned out the most egregious cases of this.

**Comment by CorpHackRyan** [comment]
I like the multiple line of # lol, I got used to it. There's also another way to do multi lines, It's something with a slash (/\)

**Comment by patpragman** [comment]
In Python multi line comments are just a string:

"""
A
Multi
Line
Comment
"""

JavaScript uses the C stuff - \\ and \* *\ if memory serves?
