### ISSUE TITLE
When shooting, ship will stop in place if you try to move left/right

### ISSUE THREAD

**Issue by CorpHackRyan** [CorpHackRyan/RP-Spaceoids#17]
Possibly need to use an on_keydown() function for multiple key strokes that are pressed at the same time so we can get real time turning, shooting, accelerating all at the same time without effecting each other

**Comment by patpragman** [comment]
Upon thinking about this, this is a more complicated problem than we'd think.  The control logic needs quite a bit of changes to make this work.  Any ideas?  I tinkered today, but can't get it to work properly.  Maybe we would have to handle multiple key strokes at once?  Any ideas?

**Comment by patpragman** [comment]
I fixed this by reworking the control logic.  We could clean this up a bit, but it works.  Used a "counter" to time the rate of fire.

**Comment by CorpHackRyan** [comment]
Will give it a shot
