### ISSUE TITLE
TEST ISSUE-Second New Announcement

### ISSUE THREAD

**Issue by CorpHackRyan** [CorpHackRyan/RP-Spaceoids#22]
So you can create issues straight from the discussion page. This is an example of doing that. Everything below is what GitHub creates and assigns when you create an issue from a discussion (far right bottom of web page is the link to do it when within a discussion).

### Discussed in https://github.com/CorpHackRyan/RP-Spaceoids/discussions/21

<div type='discussions-op-text'>

<sup>Originally posted by **CorpHackRyan** September  9, 2021</sup>
Testing to see if this shows up in the big title bar when you click on discussions.</div>

**Comment by patpragman** [comment]
sweet - it shows up in the "issues" area.
